### ISSUE TITLE
extension is outdated for Gnome 41

### ISSUE THREAD

**Issue by chuvke** [Siroj42/gnome-extension-transparent-shell#11]
hacking a version 41 in ~/.local/share/gnome-shell/extensions/transparent-shell@siroj42.github.io/metadata.json seems to work

**Comment by ReDTerraN** [comment]
I have made a commit here: https://github.com/Siroj42/gnome-extension-transparent-shell/pull/12. but it seems the @Siroj42 might not be seeing this.
