### ISSUE TITLE
Not supported on Gnome 42

### ISSUE THREAD

**Issue by zefkerr** [Siroj42/gnome-extension-transparent-shell#14]
Hello, there's an error with "Main.panel._leftCorner is undefined". Could you fix please the extension so it will work with gnome 42?
Thanks!

**Comment by petar-v** [comment]
Hi! I have made a PR here: https://github.com/Siroj42/gnome-extension-transparent-shell/pull/13 This should make it run on Gnome 42.

**Comment by zefkerr** [comment]
> Hi! I have made a PR here: https://github.com/Siroj42/gnome-extension-transparent-shell/pull/13 This should make it run on Gnome 42.

Thank you! I will test it as soon as I can.

**Comment by zefkerr** [comment]
@Siroj42  Works fine for me since [f88e97b](https://github.com/Siroj42/gnome-extension-transparent-shell/commit/f88e97bcf9b7d2c2aa45df7068a66035d54379cd), but please update it on the extension page: https://extensions.gnome.org/extension/3518/transparent-shell/

**Comment by Siroj42** [comment]
I had to make a few adjustments to pass the review, but the updated version is now live on [extensions.gnome.org](extensions.gnome.org).
