### ISSUE TITLE
Not working on second monitor with Multi Monitors Add-On

### ISSUE THREAD

**Issue by WuerfelDev** [Siroj42/gnome-extension-transparent-shell#2]
With the [Multi Monitors Add-On Extension](https://github.com/spin83/multi-monitors-add-on) only the main monitor has the transparency.
Don't know if that's fixable, as many extensions are not modifying the second monitor with that extension.

![Screenshot from 2020-09-09 11-01-26](https://user-images.githubusercontent.com/12686819/92578689-7d509e00-f28c-11ea-9ce0-90df82d64e80.png)

**Comment by Siroj42** [comment]
This works now, but it's only in the GitHub version. It will take a bit until the update is accepted at extensions.gnome.org. Also, for the panel to work, you might have to disable and then re-enable the extension if the Multi Monitors Add-On extension is loaded first.
